
title: Open Coding
description: "Class of 2026"
owner_name: Open Coding Society
github_username: open-coding-society
github_repo: "pages"
baseurl: ""
future: true

remote_theme: jekyll/cayman

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
